### ISSUE TITLE
立体何切るスクリプトで例外が発生する

### ISSUE THREAD

**Issue by kobalab** [kobalab/majiang-ai#1]
```bash
$ node dev/eval_dapai.js p77s13,z111-,m789-,m444-/0/2/m8 /s6*//

/Users/koba/Git/majiang-ai/node_modules/@kobalab/majiang-core/lib/shoupai.js:356
            if (! d)                                    throw new Error(p);
                                                        ^

Error: z1
    at Shoupai.get_gang_mianzi (/Users/koba/Git/majiang-ai/node_modules/@kobalab/majiang-core/lib/shoupai.js:356:63)
    at Function.get_gang_mianzi (/Users/koba/Git/majiang-ai/node_modules/@kobalab/majiang-core/lib/game.js:1021:30)
    at Player.get_gang_mianzi (/Users/koba/Git/majiang-ai/node_modules/@kobalab/majiang-core/lib/player.js:144:29)
    at Player.select_fulou (/Users/koba/Git/majiang-ai/lib/player.js:143:31)
    at Object.<anonymous> (/Users/koba/Git/majiang-ai/dev/eval_dapai.js:160:12)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Comment by kobalab** [comment]
立体何切るスクリプトは牌の危険度を計算するために副露面子からも打牌を再現するが、自分が鳴いた `z1` の打牌に対して本来不要な副露判定をしようとし、エラーが発生している。

副露された打牌に対して副露判定しないよう修正する。

**Comment by kobalab** [comment]
v1.0.1 に反映。
